"""Add webhook deliveries table

Revision ID: f1e2d3c4b5a7
Revises: f1e2d3c4b5a6
Create Date: 2026-06-23 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from open_webui.internal.db import JSONField


# revision identifiers, used by Alembic.
revision = 'f1e2d3c4b5a7'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'webhook_delivery',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('event_data', JSONField(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False, server_default='pending'),
        sa.Column('retries', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_delivery')
    # ### end Alembic commands ###
